### ISSUE TITLE
Perfect/Zero items

### ISSUE THREAD

**Issue by LCisannoyed** [markdly/conquestr#11]
function conquestr::cq_itanal() fails to read in any itanal file that contains a zero/perfect item.
Error message is something about True/FALSE
![image](https://user-images.githubusercontent.com/8520783/39413347-1f9eaa0e-4c6c-11e8-9a6e-d09c0bf7d3e9.png)

Sample itanal stats:     
![image](https://user-images.githubusercontent.com/8520783/39413371-899026cc-4c6c-11e8-853e-0bcb6a06e629.png)

**Comment by markdly** [comment]
To help resolve this can you add the itanal stats as raw text rather than an image? 

I only need what's shown in the image not the whole itanal file.

Thanks

**Comment by LCisannoyed** [comment]
Item 106
--------
item:106 (Y5_x00076574-GP_E1)                                                   
Cases for this item    357   Discrimination NA
Item Threshold(s): NOT AVAILABLE   Weighted MNSQ: NOT AVAILABLE
Item Delta(s): NOT AVAILABLE
------------------------------------------------------------------------------
 Label    Score     Count   % of tot  Pt Bis     t  (p)   PV1Avg:1 PV1 SD:1   
------------------------------------------------------------------------------
   0       0.00      356      99.72    0.05     0.95(.341) -0.27     0.98     
   9       0.00        1       0.28   -0.05    -0.95(.341) -0.92     0.00     
==============================================================================

**Comment by LCisannoyed** [comment]
hmm, the format is a bit funky, but if you click the 'edit comment '  button you will get the real txt

**Comment by markdly** [comment]
you can just enclose the text like a code block (``` before and after the text) to render in a nicer way.  i.e.: 
```
Item 106
--------
item:106 (Y5_x00076574-GP_E1)                                                   
Cases for this item    357   Discrimination NA
Item Threshold(s): NOT AVAILABLE   Weighted MNSQ: NOT AVAILABLE
Item Delta(s): NOT AVAILABLE
------------------------------------------------------------------------------
 Label    Score     Count   % of tot  Pt Bis     t  (p)   PV1Avg:1 PV1 SD:1   
------------------------------------------------------------------------------
   0       0.00      356      99.72    0.05     0.95(.341) -0.27     0.98     
   9       0.00        1       0.28   -0.05    -0.95(.341) -0.92     0.00     
==============================================================================
```

**Comment by markdly** [comment]
And thanks. That will do nicely...

**Comment by LCisannoyed** [comment]
yeah, that would have been nicer. thx for the tip

**Comment by markdly** [comment]
That's actually importing OK for me. 

Can you try rerunning just the first two lines and see if that generates an error? (i.e. leave out `df %<>% mutate...` onwards?

**Comment by LCisannoyed** [comment]
hmm, no issue for me either. 
I will find the **exact** file from this morning

**Comment by LCisannoyed** [comment]
```
Item 25
-------
item:25 (x00076574)                                                             
Cases for this item    356   Discrimination NA
Item Threshold(s): NOT AVAILABLE   Weighted MNSQ: NOT AVAILABLE
Item Delta(s): NOT AVAILABLE
------------------------------------------------------------------------------
 Label    Score     Count   % of tot  Pt Bis     t  (p)   PV1Avg:1 PV1 SD:1   
------------------------------------------------------------------------------
   0       0.00      356     100.00     NA       NA (.000) -0.22     0.96     
==============================================================================
```

**Comment by LCisannoyed** [comment]
i assume because the pbs is NA?

**Comment by markdly** [comment]
If you update your version of `conquestr` this should hopefully work now. You will still get a warning though to indicate there was something other than numeric in the ptbis field etc...

**Comment by LCisannoyed** [comment]
perfect! thanks for fixing this
