### ISSUE TITLE
rlang package needed

### ISSUE THREAD

**Issue by LCisannoyed** [markdly/conquestr#6]
I tried to install the conquestr package and got an error about the rlang package 
i resolved it by `install.package("rlang")` and then re-trying to install your CQr package

**> devtools::install_github("markdly/conquestr")**

Downloading GitHub repo markdly/conquestr@master
from URL https://api.github.com/repos/markdly/conquestr/zipball/master
Installing conquestr
Installing 1 package: gdata
Installing package into ‘C:/Users/Leanne/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependency ‘gtools’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/gtools_3.5.0.zip'
Content type 'application/zip' length 144747 bytes (141 KB)
downloaded 141 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/gdata_2.18.0.zip'
Content type 'application/zip' length 1186723 bytes (1.1 MB)
downloaded 1.1 MB

package ‘gtools’ successfully unpacked and MD5 sums checked
package ‘gdata’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Leanne\AppData\Local\Temp\RtmpWaqULs\downloaded_packages
Installing 1 package: rlang
Installing package into ‘C:/Users/Leanne/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rlang_0.2.0.zip'
Content type 'application/zip' length 817350 bytes (798 KB)
downloaded 798 KB

package ‘rlang’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘rlang’

The downloaded binary packages are in
	C:\Users\Leanne\AppData\Local\Temp\RtmpWaqULs\downloaded_packages
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  "C:/Users/Leanne/AppData/Local/Temp/RtmpWaqULs/devtoolsf503a325c1b/markdly-conquestr-c414fbd"  \
  --library="C:/Users/Leanne/Documents/R/win-library/3.4" --install-tests 

ERROR: dependency 'rlang' is not available for package 'conquestr'
* removing 'C:/Users/Leanne/Documents/R/win-library/3.4/conquestr'
In R CMD INSTALL
Installation failed: Command failed (1)`

**Comment by markdly** [comment]
Looks like the install issue is related to the line

`Warning: cannot remove prior installation of package ‘rlang’`

This [SO question](https://stackoverflow.com/questions/26570912/error-in-installation-a-r-package) may be related. 

Closing for now but will reopen if this issue persists...
